advanced:
  auto_optimize_index: true
  index_refresh_interval: 3600
  max_cached_results: 1000
  optimize_interval: 86400
  whoosh_mem_limit: 512
file_scanner:
  exclude_patterns: .git;.svn;.hg;__pycache__;.idea;.vscode;node_modules;venv;env;.DS_Store;Thumbs.db
  file_types:
    archive: .zip,.rar,.7z,.tar,.gz
    audio: .mp3,.wav,.flac,.ogg,.m4a
    document: .txt,.md,.pdf,.doc,.docx,.xls,.xlsx,.ppt,.pptx,.csv,.json,.xml
    image: .jpg,.jpeg,.png,.gif,.bmp,.tiff,.svg
    video: .mp4,.avi,.mov,.mkv,.wmv
  max_file_size: 100
  recursive: true
  scan_paths: '~'
  scan_threads: 4
interface:
  auto_save_settings: true
  font_size: 12
  language: zh_CN
  max_preview_size: 5242880
  result_columns:
  - 文件名
  - 路径
  - 匹配度
  - 修改时间
  splitter_pos: 300
  theme: dark
model:
  embedding_model: all-MiniLM-L6-v2
  enabled: false
  max_tokens: 2048
  model_path: ''
  temperature: 0.7
  use_gpu: false
monitor:
  debounce_time: 0.5
  directories: '~'
  enabled: false
  ignored_patterns: .git;.svn;.hg;__pycache__;.idea;.vscode;node_modules;venv;env;.DS_Store;Thumbs.db
  refresh_interval: 1
search:
  cache_ttl: 3600
  highlight: true
  max_results: 50
  min_score: 0.3
  text_weight: 0.5
  vector_weight: 0.5
system:
  app_name: 智能文件检索与问答系统
  cache_dir: ./data/cache
  data_dir: ./data
  index_dir: ./data/index
  log_backup_count: 5
  log_dir: ./data/logs
  log_level: INFO
  log_max_size: 10
  log_rotation: midnight
  temp_dir: ./data/temp
  version: 1.0.0
