version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000" # FastAPI
      - "8501:8501" # Streamlit
    environment:
      - NLP_MODEL_NAME=paraphrase-multilingual-MiniLM-L12-v2
      - FAISS_INDEX_PATH=/app/data/faiss_index
    volumes:
      - ./data:/app/data
      - ./docs:/app/docs
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  # 如果有数据库服务可以取消注释以下配置
  # db:
  #   image: postgres:15
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: admin
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: filetools
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U admin"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 5

volumes:
  pgdata:
